language: go
go:
  - "1.12.7"
services: postgresql
install:
  - make schema
before_script:
  - psql -c 'create database test_inkster;' -U postgres
  - go run migrations/*.go up
script:
  - go test ./... -p 1 -coverprofile=/tmp/go-code-cover
env:
  global:
    - GO111MODULE=on
    - PG_HOST=postgres://postgres@localhost:5432/test_inkster?sslmode=disable
    - SECRET=secret
addons:
  postgresql: 9.6
