language: go
go: 
  - "1.10.1"
  - master
node_js:
  - "8.11.1"
  - master
cache:
  directories:
    - node_modules
before_install:                                                                 
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  
install:
  - dep ensure
script:
  - go test ./... -coverprofile=/tmp/go-code-cover
services: mongodb
env:
  global:
    - INKSTER_DB_URI=mongodb://inkster:inkster@db/admin
    - INKSTER_DB_NAME=inkster
    - INKSTER_PORT=8000 
    - INKSTER_STATIC=static
    - INKSTER_SERVE_STATIC=1
