language: go
go: 
  - "1.10.1"
  - master
node_js:
  - "8.11.1"
  - master
cache:
  directories:
    - node_modules
before_install:                                                                 
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  
install:
  - dep ensure
  - npm i
before_script:
  - psql -c 'create database inkster;' -U postgres
script:
  - go test ./... -coverprofile=/tmp/go-code-cover
  # - npm test
services: postgresql
env:
  global:
    - INKSTER_DB_PORT=5432
    - INKSTER_DB_ADDR="127.0.0.1"
    - INKSTER_DB_NAME=inkster
    - INKSTER_DB_USER=travis
    - INKSTER_DB_USER_PASSWORD=
