language: go
go: 
  - "1.12.7"
services: postgresql
install:                                                                 
  - make schema
before_script:
  - psql -c 'create database test_inkster;' -U postgres
  - go run migrations/*.go up
script:
  - GOCACHE=off go test ./... -p 1 -coverprofile=/tmp/go-code-cover
env:
  global:
    - POSTGRES_HOST=postgres://postgres@localhost:5432/test_inkster?sslmode=disable
    - INKSTER_PORT=8000 
    - INKSTER_STATIC=$TRAVIS_BUILD_DIR/static
    - INKSTER_SECRET_KEY=secret
addons:
  postgresql: 9.6
