language: go
go: 
  - "1.10.1"
node_js:
  - "8.11.2"
services: postgresql
install:                                                                 
  - make schema
before_script:
  - psql -c 'create database test_inkster;' -U postgres
  - go run migrations/*.go up
script:
  - GOCACHE=off go test ./... -p 1 -coverprofile=/tmp/go-code-cover
  - npm i && npm run build
env:
  global:
    - POSTGRES_HOST=postgres://postgres@localhost:5432/test_inkster?sslmode=disable
    - INKSTER_PORT=8000 
    - INKSTER_STATIC=$TRAVIS_BUILD_DIR/static
    - INKSTER_SECRET_KEY=secret
addons:
  postgresql: 9.6
