language: go
go: 
  - "1.10.1"
  - master
node_js:
  - "8.11.1"
  - master
services: postgresql
install:                                                                 
  - make schema
before_script:
  - sleep 15
script:
  - GOCACHE=off go test ./... -p 1 -coverprofile=/tmp/go-code-cover
  - cd panel && npm i && npm run build
env:
  global:
    - POSTGRES_HOST=postgres://postgres@localhost:5432/inkster?sslmode=disable
    - INKSTER_PORT=8000 
    - INKSTER_STATIC=$TRAVIS_BUILD_DIR/static
