version: '2'
services: 
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=inkster
      - MONGO_INITDB_ROOT_PASSWORD=inkster
      - MONGO_INITDB_DATABASE=inkster
  pg:
    image: library/postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=inkster
      - POSTGRES_PASSWORD=inkster
      - POSTGRES_MULTIPLE_DATABASES=test_inkster
    volumes:
      - ./postgres/docker:/docker-entrypoint-initdb.d
  web:
    links:
      - db
    depends_on:
      - db
    build: .
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_USER=inkster
      - POSTGRES_PASSWORD=inkster
      - INKSTER_DB_URI=mongodb://inkster:inkster@db/admin
      - INKSTER_DB_NAME=inkster
      - INKSTER_PORT=8000 
      - INKSTER_STATIC=static
      - INKSTER_SERVE_STATIC=1
      - INKSTER_DEBUG=1
      - INKSTER_SMTP_HOST=dummy
      - INKSTER_SMTP_LOGIN=dummy
      - INKSTER_SMTP_ADDR=dummy
      - INKSTER_SMTP_PASS=dummy
      - INKSTER_SMTP_PORT=dummy
    volumes:
      - ./panel/build:/go/src/app/panel/build
