version: '2'
services: 
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foxxy
      - MONGO_INITDB_ROOT_PASSWORD=foxxy
      - MONGO_INITDB_ROOT_DATABASE=foxxy
  web:
    links:
      - db
    depends_on:
      - db
    build: .
    ports:
      - '8000:8000'
    environment:
      - FOXXY_DB_URI=mongodb://foxxy:foxxy@db/admin
      - FOXXY_DB_NAME=foxxy
      - FOXXY_PORT=8000
    volumes:
      - ./panel/build:/go/src/app/panel/build
    command: "/app/main" 
