required = ["github.com/jteeuwen/go-bindata"]

[[constraint]]
  branch = "master"
  name = "github.com/graph-gophers/graphql-go"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/dchest/uniuri"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"
